//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "AccountScreen.xaml.h"

void ::SimpleBank::AccountScreen::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///AccountScreen.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::SimpleBank::AccountScreen::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 1:
        {
            this->___no_name_ = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 2:
        {
            this->lab_UserName = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 3:
        {
            this->bt_Logout = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->bt_Logout))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpleBank::AccountScreen::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AccountScreen::bt_Logout_Click);
        }
        break;
    case 4:
        {
            this->pbx_AddAccnt = safe_cast<::Windows::UI::Xaml::Controls::Primitives::Popup^>(__target);
        }
        break;
    case 5:
        {
            this->pbx_Transfer = safe_cast<::Windows::UI::Xaml::Controls::Primitives::Popup^>(__target);
        }
        break;
    case 6:
        {
            this->pbx_MakePayment = safe_cast<::Windows::UI::Xaml::Controls::Primitives::Popup^>(__target);
        }
        break;
    case 7:
        {
            this->lab_OverdraftLimit = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 8:
        {
            this->bt_Withdraw = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->bt_Withdraw))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpleBank::AccountScreen::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AccountScreen::bt_Withdraw_Click);
        }
        break;
    case 9:
        {
            this->tb_Withdraw = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 10:
        {
            this->bt_Deposit = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->bt_Deposit))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpleBank::AccountScreen::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AccountScreen::bt_Deposit_Click);
        }
        break;
    case 11:
        {
            this->tb_Deposit = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 12:
        {
            this->bt_MakePayment = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->bt_MakePayment))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpleBank::AccountScreen::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AccountScreen::bt_MakePayment_Click);
        }
        break;
    case 13:
        {
            this->bt_Transfer = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->bt_Transfer))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpleBank::AccountScreen::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AccountScreen::bt_Transfer_Click);
        }
        break;
    case 14:
        {
            this->sp_ActivityLogLeft = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 15:
        {
            this->sp_ActivityLogCen = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 16:
        {
            this->sp_ActivityLogRight = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 17:
        {
            this->lab_Balance = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 18:
        {
            this->lab_AccNumber = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 19:
        {
            this->sp_AccountList = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 20:
        {
            this->bt_AddAccount = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->bt_AddAccount))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpleBank::AccountScreen::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AccountScreen::bt_AddAccount_Click);
        }
        break;
    case 21:
        {
            this->grd_Payment = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 22:
        {
            this->sp_PaymentMain = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 23:
        {
            this->lab_PaymentAccNum = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 24:
        {
            this->tb_PaymentAccNum = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 25:
        {
            this->lab_PaymentAmount = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 26:
        {
            this->tb_PaymentAmount = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 27:
        {
            this->bt_PaymentAccept = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->bt_PaymentAccept))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpleBank::AccountScreen::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AccountScreen::bt_PaymentAccept_Click);
        }
        break;
    case 28:
        {
            this->bt_PaymentCancel = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->bt_PaymentCancel))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpleBank::AccountScreen::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AccountScreen::bt_PaymentCancel_Click);
        }
        break;
    case 29:
        {
            this->grd_Transfer = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 30:
        {
            this->sp_TransferMain = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 31:
        {
            this->sp_TransferList = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 32:
        {
            this->lab_TransAmount = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 33:
        {
            this->tb_transAmount = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
        }
        break;
    case 34:
        {
            this->bt_TransAccept = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->bt_TransAccept))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpleBank::AccountScreen::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AccountScreen::bt_TransAccept_Click);
        }
        break;
    case 35:
        {
            this->bt_TransCancel = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->bt_TransCancel))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpleBank::AccountScreen::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AccountScreen::bt_TransCancel_Click);
        }
        break;
    case 36:
        {
            this->bt_Close = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->bt_Close))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpleBank::AccountScreen::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AccountScreen::bt_Close_Click);
        }
        break;
    case 37:
        {
            this->bt_createStud = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->bt_createStud))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpleBank::AccountScreen::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AccountScreen::bt_createStud_Click);
        }
        break;
    case 38:
        {
            this->bt_createSave = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->bt_createSave))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpleBank::AccountScreen::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AccountScreen::bt_createSave_Click);
        }
        break;
    case 39:
        {
            this->bt_createCurr = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->bt_createCurr))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SimpleBank::AccountScreen::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&AccountScreen::bt_createCurr_Click);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::SimpleBank::AccountScreen::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


