#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
                ref class Button;
                ref class PasswordBox;
                ref class TextBox;
            }
        }
    }
}

namespace SimpleBank
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::TextBlock^ lab_title;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ lab_exp;
        private: ::Windows::UI::Xaml::Controls::Button^ bt_login;
        private: ::Windows::UI::Xaml::Controls::PasswordBox^ pb_password;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ lab_passerror;
        private: ::Windows::UI::Xaml::Controls::TextBox^ tb_userid;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ lab_iderror;
    };
}

